[tool.poetry]
name = "mydjangoapp"
version = "0.1.0"
description = ""
authors = ["Notf8 <notf8@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
