# Generated by Django 4.0.6 on 2023-07-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
